# Generated by Django 6.0.4 on 2026-04-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=100, verbose_name='')),
                ('description_cat', models.TextField(verbose_name='')),
                ('image_cat', models.ImageField(upload_to='category/', verbose_name='')),
                ('slug_cat', models.SlugField(unique=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('price', models.PositiveIntegerField(verbose_name='')),
                ('image', models.ImageField(upload_to='category/', verbose_name='')),
                ('slug', models.SlugField(unique=True, verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-created'],
            },
        ),
    ]
