# Generated by Django 6.0.4 on 2026-04-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AddField(
            model_name='country',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='main.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='country',
            name='hotel',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отель'),
        ),
        migrations.AddField(
            model_name='country',
            name='insurance',
            field=models.BooleanField(default=True, verbose_name='Медицинская страховка'),
        ),
        migrations.AddField(
            model_name='country',
            name='meal',
            field=models.CharField(choices=[('BB', 'Завтраки'), ('HB', 'Завтрак + ужин'), ('FB', '3-разовое питание'), ('AI', 'Всё включено')], default='BB', max_length=50, verbose_name='Питание'),
        ),
        migrations.AddField(
            model_name='country',
            name='nights',
            field=models.IntegerField(default=7, verbose_name='Количество ночей'),
        ),
        migrations.AddField(
            model_name='country',
            name='stars',
            field=models.IntegerField(choices=[(1, '1★'), (2, '2★'), (3, '3★'), (4, '4★'), (5, '5★')], default=3, verbose_name='Звёздность отеля'),
        ),
        migrations.AddField(
            model_name='country',
            name='transfer',
            field=models.BooleanField(default=True, verbose_name='Трансфер включён'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_cat',
            field=models.TextField(verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_cat',
            field=models.ImageField(upload_to='category/', verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_cat',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_cat',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='country',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(verbose_name='Описание тура'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(upload_to='countries/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название тура'),
        ),
        migrations.AlterField(
            model_name='country',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена (₽)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
