# Generated by Django 6.0.4 on 2026-04-17 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_country_options_country_cat_country_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='main.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
